version: '3.4'

services:
  logging-api:
    container_name: logging-api
    build: .
    restart: always
    ports:
      - "90:90"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    expose:
      - "5455"
    ports:
      - "5455:5455"
    volumes:
      - backendDB:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: LoggingDB

volumes:
  backendDB: 