version: '3.4'

networks:
  loggingapi-dev:
    driver: bridge 

services:
  logging-api:
    image: logging-api:latest
    depends_on:
      - "mongodb"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"     
    environment:
      MONGODB_URL: "mongodb://mongo:nMydqJHhrAG84mXGLxkH@mongodb:27017/?authMechanism=SCRAM-SHA-256"
    networks:
      - loggingapi-dev  
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: nMydqJHhrAG84mXGLxkH
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - loggingapi-dev

volumes:
  mongodb-data: