version: '3.4'

networks:
  loggingapi-dev:
    driver: bridge 

services:
  logging-api:
    image: logging-api:latest
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "90:90"     
    environment:
      DB_CONNECTION_STRING: "Server=db;Database=LoggingDB;Port=5455;User Id=postgres;Password=nMydqJHhrAG84mXGLxkH"
    networks:
      - loggingapi-dev  
  
  db:
    image: postgres:latest
    ports:
      - "5455"
    restart: always
    volumes:
      - backendDB:/data/db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "nMydqJHhrAG84mXGLxkH"
      POSTGRES_DB: "LoggingDB"
    networks:
      - loggingapi-dev
volumes:
  backendDB: