
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.ActionLogs (
    Id integer NOT NULL,
    User_Id character varying(50) NOT NULL,
    Action text NOT NULL,
    Prev_Value text NOT NULL,
    New_Value text NOT NULL,
    Unit_Type character varying(100) NOT NULL,
    Date timestamp without time zone NOT NULL,
    Source text NOT NULL
);


ALTER TABLE public.ActionLogs OWNER TO postgres;


ALTER TABLE public.ActionLogs ALTER COLUMN Id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ActionLogs_Id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.BackendLogs (
    Id integer NOT NULL,
    Message text NOT NULL,
    Date timestamp without time zone NOT NULL,
    User_Id character varying(50) NOT NULL,
    Source character varying(300) NOT NULL
);


ALTER TABLE public.BackendLogs OWNER TO postgres;


ALTER TABLE public.BackendLogs ALTER COLUMN Id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.BackendLogs_Id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.FrontendLogs (
    Id integer NOT NULL,
    Message text NOT NULL,
    Date timestamp without time zone NOT NULL,
    User_Id character varying(50) NOT NULL,
    Url character varying(300) NOT NULL
);


ALTER TABLE public.FrontendLogs OWNER TO postgres;


ALTER TABLE public.FrontendLogs ALTER COLUMN Id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.FrontendLogs_Id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.Users (
    Id integer NOT NULL,
    Username text NOT NULL,
    PasswordHash bytea NOT NULL,
    PasswordSalt bytea NOT NULL
);


ALTER TABLE public.Users OWNER TO postgres;


ALTER TABLE public.Users ALTER COLUMN Id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.Users_Id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY public.ActionLogs
    ADD CONSTRAINT PK_ActionLogs PRIMARY KEY (Id);


ALTER TABLE ONLY public.BackendLogs
    ADD CONSTRAINT PK_BackendLogs PRIMARY KEY (Id);


ALTER TABLE ONLY public.FrontendLogs
    ADD CONSTRAINT PK_FrontendLogs PRIMARY KEY (Id);


ALTER TABLE ONLY public.Users
    ADD CONSTRAINT PK_Users PRIMARY KEY (Id);


